# Overall filter parameters
min_particles: 15
max_particles: 150
kld_err: 0.02
kld_z: 0.98
update_min_d: 0.1
update_min_a: 0.524 #pi/6.0
resample_interval: 2.0
transform_tolerance: 1.2
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.05
initial_cov_xx: 0.25
initial_cov_yy: 0.25
initial_cov_aa: 0.0 #pi/12 * pi/12

# Laser Model parameters
laser_min_range : -1.0
laser_max_range: -1.0
laser_max_beams: 30
laser_model_type: "likelihood_field"

# Odometry model parameters
odom_model_type: “diff-corrected”
odom_alpha1: 0.005
odom_alpha2: 0.005
odom_alpha3: 0.005
odom_alpha4: 0.01
odom_alpha5: 0.005

odom_frame_id: “odom”
base_frame_id: “base_link”
global_frame_id: “map”

