TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_theta: 0.7
  min_vel_theta: -0.7
  min_in_place_vel_theta: -0.7
  escape_vel: -0.3
  acc_lim_theta: 0.8
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  sim_time: 0.8
  sim_granularity: 0.025
  holonomic_robot: false
  yaw_goal_tolerance: 0.01
  xy_goal_tolerance: 0.0.05
  latch_xy_goal_tolerance: false
  controller_frequency: 1.0
  occdist_scale: 0.05
  pdist_scale: 0.8
